#crab submit -c crabConfig_MC_JERCL5_DilepTTBar.py
crab submit -c crabConfig_MC_JERCL5_DYJets_0J.py
crab submit -c crabConfig_MC_JERCL5_DYJets_1J.py
crab submit -c crabConfig_MC_JERCL5_DYJets_2J.py
crab submit -c crabConfig_MC_JERCL5_DYJets_LowMass.py
crab submit -c crabConfig_MC_JERCL5_DYJets.py
#crab submit -c crabConfig_MC_JERCL5_HadTTBar.py
#crab submit -c crabConfig_MC_JERCL5_QCD_CP5.py
#crab submit -c crabConfig_MC_JERCL5_SemilepTTBar.py
crab submit -c crabConfig_MC_JERCL5_ST_s_thad.py
crab submit -c crabConfig_MC_JERCL5_ST_s_tlep.py 
crab submit -c crabConfig_MC_JERCL5_ST_t_atop.py
crab submit -c crabConfig_MC_JERCL5_ST_t_top.py
crab submit -c crabConfig_MC_JERCL5_ST_tW_atop.py
crab submit -c crabConfig_MC_JERCL5_ST_tW_top.py
crab submit -c crabConfig_MC_JERCL5_WJets_2J.py
#crab submit -c crabConfig_MC_JERCL5_WW.py
#crab submit -c crabConfig_MC_JERCL5_WZ.py
#crab submit -c crabConfig_MC_JERCL5_ZZ.py
#crab submit -c crabConfig_MC_JERCL5_bQCD_MG1000to1500.py
#crab submit -c crabConfig_MC_JERCL5_QCD_MG1000to1500.py
#crab submit -c crabConfig_MC_JERCL5_bQCD_MG1500to2000.py
#crab submit -c crabConfig_MC_JERCL5_QCD_MG1500to2000.py
#crab submit -c crabConfig_MC_JERCL5_bQCD_MG2000toInf.py
#crab submit -c crabConfig_MC_JERCL5_QCD_MG2000toInf.py
#crab submit -c crabConfig_MC_JERCL5_TTBar_Mtt700to1000.py
#crab submit -c crabConfig_MC_JERCL5_TTBar_Mtt1000toInf.py
#crab submit -c crabConfig_MC_JERCL5_TTBar_PHH7.py
